No dia de hoje aprendi sobre o fluxo de exceção e como usá-lo para prever e controlar erros no código, afim de deixá-lo mais utilizável para o usuário. Utilizando as funções throw, try, catch e finally, posso criar meu próprio erro para então tratá-lo e dar uma finalidade no mesmo, tornando o código melhor. Nos exercícios coloquei em prática o conteúdo treinando a utilização destas funções.